zookeeper:
  image: eventuateio/eventuateio-local-zookeeper:0.30.0.M14
  ports:
    - 2181:2181
    - 2888:2888
    - 3888:3888


kafka:
  image: test-eventuateio-local-kafka
  ports:
    - 9092:9092
  links:
    - zookeeper
  environment:
    - ADVERTISED_HOST_NAME=${DOCKER_HOST_IP}
    - KAFKA_HEAP_OPTS=-Xmx320m -Xms320m
    - ZOOKEEPER_SERVERS=zookeeper:2181

activemq:
  image: webcenter/activemq:5.14.3
  ports:
    - 8161:8161
    - 61616:61616
    - 61613:61613
    - 1883:1883
    - 61614:61614

rabbitmq:
  build: ./rabbitmq
  ports:
    - 5672:5672

mysqlbinlogpipeline:
  build: ./mysql
  ports:
    - 3306:3306
  environment:
    - MYSQL_ROOT_PASSWORD=rootpassword
    - MYSQL_USER=mysqluser
    - MYSQL_PASSWORD=mysqlpw

postgrespollingpipeline:
  build: ./postgres
  ports:
    - 5432:5432
  environment:
    POSTGRES_USER: eventuate
    POSTGRES_PASSWORD: eventuate

postgreswalpipeline:
  build: ./postgres
  ports:
    - 5433:5432
  environment:
    POSTGRES_USER: eventuate
    POSTGRES_PASSWORD: eventuate