version: 2
jobs:
  build:
    machine: true
    working_directory: ~/eventuate-tram-core
    steps:
      - checkout
      - restore_cache:
          key: eventuate-tram-core-{{ checksum "build.gradle" }}
      - run: TERM=dumb ./gradlew testClasses
      - save_cache:
          paths:
            - ~/.gradle
          key: eventuate-tram-core-{{ checksum "build.gradle" }}
      - run: TERM=dumb ./build-and-test-all-mysql.sh
      - run: TERM=dumb ./build-and-test-all-cdc-mysql.sh
      - run: TERM=dumb ./build-and-test-all-postgres-polling.sh
      - run: TERM=dumb ./build-and-test-all-postgres-wal.sh
      - run: TERM=dumb ./build-and-test-all-cdc-postgres-polling.sh
      - run: TERM=dumb ./build-and-test-all-cdc-postgres-wal.sh
      - run:
          name: Save test results
          command: |
            mkdir -p ~/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/junit/ \;
          when: always
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/junit
      - run:
          name: Publish artifacts
          command: |
            TERM=dumb ./deploy-artifacts.sh
          when: on_success
